/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.apercova.jencoderui.ui;

import io.apercova.jencoderui.controller.MainViewController;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author alonperezext
 */
public class MainView extends javax.swing.JFrame {

    private final MainViewController controller;
    /**
     * Creates new form MainView
     */
    public MainView() {
        
        initComponents();        
        initCustomComponents();
        this.controller = new MainViewController(this);
        this.chkFile.addActionListener(this.controller);
        this.btnFileChooser.addActionListener(this.controller);
        this.btnDigest.addActionListener(this.controller);
        this.btnEncode.addActionListener(this.controller);
        this.btnCopyResult.addActionListener(this.controller);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAlg = new javax.swing.JLabel();
        lblEncoding = new javax.swing.JLabel();
        lblCharset = new javax.swing.JLabel();
        btnEncode = new javax.swing.JButton();
        btnDigest = new javax.swing.JButton();
        btnCopyResult = new javax.swing.JButton();
        cmbAlg = new javax.swing.JComboBox();
        cmbEncoding = new javax.swing.JComboBox();
        cmbCharset = new javax.swing.JComboBox();
        btnFileChooser = new javax.swing.JButton();
        chkFile = new javax.swing.JCheckBox();
        lblSource = new javax.swing.JLabel();
        btnCopySource = new javax.swing.JButton();
        btnClSource = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        btnClResult = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        scrollSource = new javax.swing.JScrollPane();
        txtSource = new javax.swing.JTextArea();
        scrollTarget = new javax.swing.JScrollPane();
        txtTarget = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        lblAlg.setText("Algorithm");

        lblEncoding.setText("Encoding");

        lblCharset.setText("Charset");

        btnEncode.setText("Encode");

        btnDigest.setText("Digest");

        btnCopyResult.setText("Copy");

        cmbAlg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbEncoding.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCharset.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFileChooser.setText("Select ...");

        chkFile.setText("File");

        lblSource.setText("Source:");

        btnCopySource.setText("Copy");

        btnClSource.setText("Clear");

        lblResult.setText("Result:");

        btnClResult.setText("Clear");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbAlg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEncoding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEncoding, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCharset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCharset, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chkFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDigest, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCopyResult, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEncode, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(btnClResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResult)
                            .addComponent(lblSource))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCopySource, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFile)
                    .addComponent(btnFileChooser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAlg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEncoding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEncoding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCharset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCharset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDigest)
                    .addComponent(btnEncode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCopySource)
                    .addComponent(btnClSource))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClResult)
                    .addComponent(btnCopyResult))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerLocation(280);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        txtSource.setColumns(20);
        txtSource.setRows(5);
        scrollSource.setViewportView(txtSource);

        jSplitPane1.setTopComponent(scrollSource);

        txtTarget.setColumns(20);
        txtTarget.setRows(5);
        scrollTarget.setViewportView(txtTarget);

        jSplitPane1.setRightComponent(scrollTarget);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {
        this.chkFile.setActionCommand(MainViewController.FILEC_CK);
        this.btnFileChooser.setActionCommand(MainViewController.FILEC_AC);
        this.btnFileChooser.setEnabled(false);
        this.btnDigest.setActionCommand(MainViewController.DIGEST_AC);
        this.btnEncode.setActionCommand(MainViewController.ENCODE_AC);
        this.btnCopyResult.setActionCommand(MainViewController.COPY_RESULT_AC);
        this.fcSource = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
    }
    
    public JTextArea getTxtSource() {
        return txtSource;
    }

    public JTextArea getTxtTarget() {
        return txtTarget;
    }

    public JLabel getLblAlg() {
        return lblAlg;
    }

    public JLabel getLblCharset() {
        return lblCharset;
    }

    public JLabel getLblEncoding() {
        return lblEncoding;
    }

    public JLabel getLblSource() {
        return lblSource;
    }

    public JLabel getLblResult() {
        return lblResult;
    }

    public JComboBox getCmbAlg() {
        return cmbAlg;
    }

    public JComboBox getCmbCharset() {
        return cmbCharset;
    }

    public JComboBox getCmbEncoding() {
        return cmbEncoding;
    }

    public JCheckBox getChkFile() {
        return chkFile;
    }

    public JButton getBtnFileChooser() {
        return btnFileChooser;
    }

    public JButton getBtnEncode() {
        return btnEncode;
    }

    public JButton getBtnDigest() {
        return btnDigest;
    }

    public JFileChooser getFcSource() {
        return fcSource;
    }
    
    public JButton getBtnCopySource() {
        return btnCopySource;
    }

    public JButton getBtnClSource() {
        return btnClSource;
    }
    
    public JButton getBtnCopyResult() {
        return btnCopyResult;
    }

    public JButton getBtnClResult() {
        return btnClResult;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClResult;
    private javax.swing.JButton btnClSource;
    private javax.swing.JButton btnCopyResult;
    private javax.swing.JButton btnCopySource;
    private javax.swing.JButton btnDigest;
    private javax.swing.JButton btnEncode;
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JCheckBox chkFile;
    private javax.swing.JComboBox cmbAlg;
    private javax.swing.JComboBox cmbCharset;
    private javax.swing.JComboBox cmbEncoding;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAlg;
    private javax.swing.JLabel lblCharset;
    private javax.swing.JLabel lblEncoding;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSource;
    private javax.swing.JScrollPane scrollSource;
    private javax.swing.JScrollPane scrollTarget;
    private javax.swing.JTextArea txtSource;
    private javax.swing.JTextArea txtTarget;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFileChooser fcSource;
}
